# Generated by Django 3.2 on 2021-04-07 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'areas',
                'db_table': 'area',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('tipo_valor', models.CharField(choices=[('%', 'Porcentagem'), ('F', 'Decimal'), ('I', 'Inteiro')], max_length=1)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='main.area')),
            ],
            options={
                'verbose_name_plural': 'metas',
                'db_table': 'meta',
                'ordering': ['prazo', 'area', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='PermissaoMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissao', to='main.meta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissao_meta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'permissoes_metas',
                'db_table': 'permissao_meta',
                'ordering': ['meta', 'usuario'],
            },
        ),
        migrations.CreateModel(
            name='PermissaoArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissao', to='main.area')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissao_area', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'permissoes_areas',
                'db_table': 'permissao_area',
                'ordering': ['area', 'usuario'],
            },
        ),
        migrations.CreateModel(
            name='MetaHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_historico', to='main.meta')),
            ],
            options={
                'verbose_name_plural': 'metas_historico',
                'db_table': 'meta_historico',
                'ordering': ['data', 'meta'],
            },
        ),
    ]
