# Generated by Django 3.2 on 2021-04-07 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'areas_permissions',
                'db_table': 'area_permisson',
                'ordering': ['area', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('value_type', models.CharField(choices=[('%', 'Porcentagem'), ('F', 'Decimal'), ('I', 'Inteiro')], max_length=1)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'goals',
                'db_table': 'goal',
                'ordering': ['due_date', 'area', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GoalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_history', to='main.goal')),
            ],
            options={
                'verbose_name_plural': 'goals_history',
                'db_table': 'goal_history',
                'ordering': ['date', 'goal'],
            },
        ),
        migrations.CreateModel(
            name='GoalPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='main.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'goals_permissions',
                'db_table': 'goal_permission',
                'ordering': ['goal', 'user'],
            },
        ),
        migrations.RemoveField(
            model_name='metahistorico',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='permissaoarea',
            name='area',
        ),
        migrations.RemoveField(
            model_name='permissaoarea',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='permissaometa',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='permissaometa',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name'], 'verbose_name_plural': 'areas'},
        ),
        migrations.RenameField(
            model_name='area',
            old_name='nome',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Meta',
        ),
        migrations.DeleteModel(
            name='MetaHistorico',
        ),
        migrations.DeleteModel(
            name='PermissaoArea',
        ),
        migrations.DeleteModel(
            name='PermissaoMeta',
        ),
        migrations.AddField(
            model_name='goal',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='main.area'),
        ),
        migrations.AddField(
            model_name='areapermission',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='main.area'),
        ),
        migrations.AddField(
            model_name='areapermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_permission', to=settings.AUTH_USER_MODEL),
        ),
    ]
