# Generated by Django 3.2 on 2021-04-07 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210407_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalhistory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
