# Generated by Django 3.2 on 2021-04-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210407_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='recurrency',
            new_name='recurrence',
        ),
    ]
